# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        java: [ '17' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.java}}
          distribution: 'adopt'
          cache: maven
          
      - name: Build with Maven Wrapper
        run: ./mvnw -B package

      - name: Test Upload
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASS: ${{ secrets.NEXUS_PASS }}
          NEXUS_URL: ${{ vars.NEXUS_BASE_URL }}
        run: curl -v -u "${{env.NEXUS_USER}}:${{env.NEXUS_PASS}}" \
          --upload-file pom.xml \
          "${{env.NEXUS_URL}}/repository/maven-snapshots/org/springframework/samples/spring-petclinic/3.1.0-SNAPSHOT/test-upload.xml"

      - name: Upload
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASS: ${{ secrets.NEXUS_PASS }}
          NEXUS_URL: ${{ vars.NEXUS_BASE_URL }}
        run: |
          curl -u "${{env.NEXUS_USER}}:${{env.NEXUS_PASS}}" -I \
            http://172.16.39.148:8081/repository/maven-snapshots/
          ./mvnw -B deploy -DskipTests -s ~/.m2/settings_nexus.xml
